### ISSUE TITLE
Drive Stats dashboard has incorrect speed units on Max Speed

### ISSUE THREAD

**Issue by chicagoandy** [teslamate-org/teslamate#4357] opened 2024-11-05 17:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Drive Stats Dashboard has a widget for Max Speed, which is nor correctly converting for mph vs KM/h

While I would love to brag about driving 161mph, but this is not correctly converting to local units (mph).   Model Y doesn't go 161mph.

![image](https://github.com/user-attachments/assets/eae66a7f-0154-49b8-b7a8-35224301fb30)

Teslamate has unit_of_length set to 'mi'

But DB values are stored in KM/h.   The UI is not converting max_speed to mph.

### Expected Behavior

UI would convert the km/h to mph before displaying the value.

### Relevant log output

```shell
s6-rc: info: service legacy-services successfully started
[16:52:16] INFO: Checking for Grafana folder: TeslaMate
[16:52:16] INFO: ... RESTORED statistics.json
[16:52:16] INFO: ... RESTORED charge-level.json
[16:52:16] INFO: ... RESTORED battery-health.json
[16:52:16] INFO: ... RESTORED states.json
[16:52:16] INFO: ... RESTORED mileage.json
[16:52:17] INFO: ... RESTORED updates.json
[16:52:17] INFO: ... RESTORED charges.json
[16:52:17] INFO: ... RESTORED locations.json
[16:52:17] INFO: ... RESTORED overview.json
[16:52:17] INFO: ... RESTORED timeline.json
[16:52:17] INFO: ... RESTORED visited.json
[16:52:17] INFO: ... RESTORED drives.json
[16:52:17] INFO: ... RESTORED projected-range.json
[16:52:17] INFO: ... RESTORED drive-stats.json
[16:52:17] INFO: ... RESTORED trip.json
[16:52:17] INFO: ... RESTORED efficiency.json
[16:52:17] INFO: ... RESTORED charging-stats.json
[16:52:17] INFO: ... RESTORED vampire-drain.json
[16:52:17] INFO: ... RESTORED drive-details.json
[16:52:17] INFO: ... RESTORED charge-details.json
[16:52:17] INFO: Finished Importing Grafana Dashboards
[16:52:17] INFO: Creating database 'teslamate' on 192.168.86.104
[16:52:17] INFO: Database teslamate already exists
[16:52:17] INFO: Starting TeslaMate...
```

### Screenshots

![image](https://github.com/user-attachments/assets/eae66a7f-0154-49b8-b7a8-35224301fb30)
![image](https://github.com/user-attachments/assets/faa71d42-a54d-40aa-bb60-24323c333928)

### Type of installation

Docker

### Version

v1.3.0

**Comment by cwanja** [comment] 2024-11-05 19:09
Duplicate of #4343 and fixed in #4338 which will be packaged and released.

**Closed** 2024-11-06 06:40 UTC
Labels: closed:duplicate
