### ISSUE TITLE
No drives reports

### ISSUE THREAD

**Issue by kris969** [teslamate-org/teslamate#2860] opened 2022-08-21 16:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm using Teslamate installed on a raspberry pi using docker and the relative docker-compose.
The actual Teslamate version is: 1.27.1
The actual Tesla version on my car is: 2022.20.8

On Teslamate, using grafana, everything seems to work fine except "drives" where reports are sometimes present but most of the time none. To compare, "drives details" is ok.

### Expected Behavior

Having all drives report visible on grafana.

### Steps To Reproduce

Just use it!

### Relevant log output

```shell
teslamate_1  | 2022-08-21 15:25:54.546 car_id=1 [info] Start / :online
teslamate_1  | 2022-08-21 15:25:54.840 car_id=1 [info] Connecting ...
teslamate_1  | 2022-08-21 15:26:25.935 [info] Start of drive initiated by: %TeslaApi.Stream.Data{elevation: 51, est_heading: 284, est_lat: 00.902658, est_lng: 0.103461, est_range: 164, heading: 283, odometer: 23950.3, power: 4, range: 203, shift_state: "R", soc: 70, speed: 0, time: ~U[2022-08-21 15:26:25.921Z]}
teslamate_1  | 2022-08-21 15:26:25.936 car_id=1 [info] Driving / Start
teslamate_1  | 2022-08-21 15:27:58.001 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (711.684 ms)
teslamate_1  | 2022-08-21 15:27:58.216 [error] Postgrex.Protocol (#PID<0.2375.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.10877.0> timed out because it queued and checked out the connection for longer than 60000ms
teslamate_1  | 
teslamate_1  | #PID<0.10877.0> was at location:
teslamate_1  | 
teslamate_1  |     :prim_inet.recv0/3
teslamate_1  |     (postgrex 0.16.3) lib/postgrex/protocol.ex:3108: Postgrex.Protocol.msg_recv/4
teslamate_1  |     (postgrex 0.16.3) lib/postgrex/protocol.ex:2138: Postgrex.Protocol.recv_bind/3
teslamate_1  |     (postgrex 0.16.3) lib/postgrex/protocol.ex:2030: Postgrex.Protocol.bind_execute/4
teslamate_1  |     (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
teslamate_1  |     (db_connection 2.4.2) lib/db_connection.ex:1364: DBConnection.run_execute/5
teslamate_1  |     (db_connection 2.4.2) lib/db_connection.ex:595: DBConnection.parsed_prepare_execute/5
teslamate_1  |     (db_connection 2.4.2) lib/db_connection.ex:587: DBConnection.prepare_execute/4
teslamate_1  | 
teslamate_1  | 2022-08-21 15:27:58.370 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (DBConnection.ConnectionError) connection is closed because of an error, disconnect or timeout
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:847: Ecto.Adapters.SQL.execute/6
teslamate_1  |     (ecto 3.8.4) lib/ecto/repo/queryable.ex:221: Ecto.Repo.Queryable.execute/4
teslamate_1  |     (ecto 3.8.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/settings.ex:14: TeslaMate.Settings.get_global_settings!/0
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/locations.ex:36: TeslaMate.Locations.find_address/1
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/log.ex:325: TeslaMate.Log.put_address/3
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/log.ex:303: TeslaMate.Log.close_drive/2
teslamate_1  | 2022-08-21 15:28:00.261 car_id=1 [info] Start / :online
teslamate_1  | 2022-08-21 15:28:00.541 car_id=1 [info] Connecting ...
teslamate_1  | 2022-08-21 15:28:09.976 [info] Start of drive initiated by: %TeslaApi.Stream.Data{elevation: 51, est_heading: 194, est_lat: 00.902623, est_lng: 0.103511, est_range: 164, heading: 196, odometer: 23950.3, power: 2, range: 202, shift_state: "D", soc: 70, speed: 0, time: ~U[2022-08-21 15:28:09.967Z]}
teslamate_1  | 2022-08-21 15:28:09.977 car_id=1 [info] Driving / Start
teslamate_1  | 2022-08-21 15:46:46.317 [error] Postgrex.Protocol (#PID<0.2371.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.11718.0> timed out because it queued and checked out the connection for longer than 60000ms
teslamate_1  | 
teslamate_1  | #PID<0.11718.0> was at location:
teslamate_1  | 
teslamate_1  |     (stdlib 3.17.2) lists.erl:1266: :lists.foldl/3
teslamate_1  |     (crypto 5.0.6.2) crypto.erl:1012: :crypto.add_cipher_aliases/1
teslamate_1  |     (crypto 5.0.6.2) crypto.erl:498: :crypto.supports/0
teslamate_1  |     (ssl 10.7.3.2) tls_record.erl:400: :tls_record.sufficient_crypto_support/1
teslamate_1  |     (ssl 10.7.3.2) ssl.erl:1319: :ssl."-versions/0-lc$^5/1-3-"/2
teslamate_1  |     (ssl 10.7.3.2) ssl.erl:1319: :ssl.versions/0
teslamate_1  |     (mint 1.4.2) lib/mint/core/transport/ssl.ex:546: Mint.Core.Transport.SSL.ssl_versions/0
teslamate_1  |     (mint 1.4.2) lib/mint/core/transport/ssl.ex:536: Mint.Core.Transport.SSL.default_ssl_opts/1
teslamate_1  | 
teslamate_1  | 2022-08-21 15:46:47.612 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (1440.740 ms)
teslamate_1  | 2022-08-21 15:46:47.629 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (DBConnection.ConnectionError) connection is closed because of an error, disconnect or timeout
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:847: Ecto.Adapters.SQL.execute/6
teslamate_1  |     (ecto 3.8.4) lib/ecto/repo/queryable.ex:221: Ecto.Repo.Queryable.execute/4
teslamate_1  |     (ecto 3.8.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate_1  |     (ecto 3.8.4) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.one/3
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/locations.ex:40: TeslaMate.Locations.find_address/1
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/log.ex:325: TeslaMate.Log.put_address/3
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/log.ex:302: TeslaMate.Log.close_drive/2
teslamate_1  | 2022-08-21 15:46:48.389 car_id=1 [info] Start / :online
teslamate_1  | 2022-08-21 15:46:48.685 car_id=1 [info] Connecting ...
teslamate_1  | 2022-08-21 15:46:48.944 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (80.072 ms)
teslamate_1  | 2022-08-21 15:46:49.216 car_id=1 [info] Charging / SOC: 68% / XXXXXX - Maison
teslamate_1  | 2022-08-21 15:46:49.216 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-08-21 16:18:00.277 [info] GET /
teslamate_1  | 2022-08-21 16:18:00.577 [info] Sent 200 in 299ms
teslamate_1  | 2022-08-21 16:18:15.151 [info] GET /settings
teslamate_1  | 2022-08-21 16:18:15.308 [info] Sent 200 in 156ms
teslamate_1  | 2022-08-21 16:23:02.400 [info] GET /
teslamate_1  | 2022-08-21 16:23:02.430 [info] Sent 200 in 29ms
```

### Type of installation

Docker

### Version

v1.27.1

**Comment by natrlhy** [comment] 2022-08-21 18:07
Have you tried this?

https://docs.teslamate.org/docs/maintenance/manually_fixing_data

**Comment by kris969** [comment] 2022-08-21 19:14
Thanks for reply ;)

Yes I did.
I used the var-drive_id+1, but I got this result that lets suppose, if I understand the log, drive has been already closed. 
cf. Log at the end of this post.

For example today, my the first two drives are well reported, but not the following ones!

Of course so far, I don't know if it's an issue due to Teslamate or a new behavior relative to the last Tesla software!
Are they people using the Tesla software 2022.20.8 without issue using Teslamate?
  

--------------------------------------------------------------------------------------------------------------------------

docker-compose exec teslamate bin/teslamate rpc     "TeslaMate.Repo.get!(TeslaMate.Log.Drive, 4208) |> TeslaMate.Log.close_drive()"
** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
    lib/ecto/adapters/sql.ex:847: Ecto.Adapters.SQL.execute/6
    lib/ecto/repo/queryable.ex:221: Ecto.Repo.Queryable.execute/4
    lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.one/3
    lib/teslamate/log.ex:292: TeslaMate.Log.close_drive/2
    (stdlib 3.17.2) erl_eval.erl:685: :erl_eval.do_apply/6

**Comment by natrlhy** [comment] 2022-08-21 19:17
I had similar issues when moving from a Pi3 to a Pi4. I ended up needing to do a backup then restore and then closing the drives. After that, they showed up on the Drives panel and all drives since then have closed without issue.

**Comment by kris969** [comment] 2022-08-21 19:26
I have a question for the community...

What are technical specifications for using Teslamate on a Rasberry Pi using docker?
My Teslamate is runnning on a Raspi version 2. 
It was working fine until a couple of weeks. Maybe my Raspi is a quite powerless to do the job?

**Comment by adriankumpf** [comment] 2022-08-23 14:33
The reason for those missing drive entries is that the recording get interrupted by a slow/overloaded/unresponsive database:

```
teslamate_1  | 2022-08-21 15:27:58.216 [error] Postgrex.Protocol (#PID<0.2375.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.10877.0> timed out because it queued and checked out the connection for longer than 60000ms
```

This can be caused by various reasons, e.g. weak hardware.

**Comment by kris969** [comment] 2022-08-23 15:25
I have done one more test.
Many drives terminated in "Drive" mode are ok. As soon as I terminate de drive in "Reverse" mode, I loose it and the following ones.
This is only an issue on the "Drives" panel, cause when I watch the "Drive details", I can see all drives.

**Closed** 2023-11-14 01:12 UTC
Labels: closed:invalid
