### ISSUE TITLE
Same name cars issue, can you  use ID-CarName or CarName (ID) on the dropdown, it's only showing 1 car

### ISSUE THREAD

**Issue by edgararroyo** [teslamate-org/teslamate#3891] opened 2024-05-13 15:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

2 cars, same name, dashboard only showing 1 on selection to pick from

### Expected Behavior

Have 2 selections on dropdown, even if same name

### Steps To Reproduce

Open dashboard, try to select vehicle, must have 2 with the same name

### Relevant log output

```shell
none
```

### Screenshots

![image](https://github.com/teslamate-org/teslamate/assets/832706/91fea97a-6b58-41ad-879f-01168e10bd08)
![image](https://github.com/teslamate-org/teslamate/assets/832706/2db773f0-0924-4e8b-87bc-dcdac1b9f7ca)

### Additional data

none

### Type of installation

Docker

### Version

1.28.5

**Comment by edgararroyo** [comment] 2024-05-13 15:34
So I edited the teslamate cars table and chagned the names and added a 1 and a 2 on respective car ID rows, it shows both and I can pick from them.  Dashboard for some reason is using the car name to pick what to show?  Should I post this elsewhere?

NOTE:  After some time, it reverted back to old name and  I could no longer pick from the lsit.  Is there a way where I can update the select statement so I can include [id] as the display name?

![image](https://github.com/teslamate-org/teslamate/assets/832706/94099f32-a308-461e-b949-0a91a8b88f2e)

![image](https://github.com/teslamate-org/teslamate/assets/832706/6ffd8225-4a75-4695-9a52-aabfbf39de40)

Dropdown shows both:
![image](https://github.com/teslamate-org/teslamate/assets/832706/04c1ae26-ed50-4f3e-8138-df17311c5da4)

**Comment by jlestel** [comment] 2024-07-08 12:34
> So I edited the teslamate cars table and chagned the names

The name is retrieved by the API.

It must therefore be defined on the vehicle to be retained.

**Comment by edgararroyo** [comment] 2024-07-08 12:40
> > So I edited the teslamate cars table and chagned the names
> 
> The name is retrieved by the API.
> 
> It must therefore be defined on the vehicle to be retained.
> 
> You can search "rename my tesla" in Google :)

**That is what I’m complaining about.** 
That is correct.  I named both cars the same.   Same names, but different IDs, so the dashboard should be able to tell apart both cars, instead it is “merging” them both and only lets me pick 1.

**Comment by DrMichael** [comment] 2024-07-08 13:39
Given, that the images show2 a Custom Dashboard, we cannot really help.

**Comment by jlestel** [comment] 2024-07-08 13:57
.. and I provided a simple workaround above.

**Comment by edgararroyo** [comment] 2024-07-08 14:02
> Given, that the images show2 a Custom Dashboard, we cannot really help.

This is on all dashboards, I just chose the custom one since it is the one I use the most.  They all work the same, they show it is querying the ID and name but it’s using the name as the “value” for the drop-down.

Here are screenshots of the stock Teslamate dashboard.

Both cars the same name (not renaming on database)
<img width="1610" alt="image" src="https://github.com/teslamate-org/teslamate/assets/832706/2f174b09-b059-44bb-a1f5-7128a8ad57eb">

Name changed in the database
<img width="1614" alt="image" src="https://github.com/teslamate-org/teslamate/assets/832706/d2656277-5662-4fed-aed8-cd92556b1c50">

**Comment by edgararroyo** [comment] 2024-07-08 14:09
> .. and I provided a simple workaround above.

I appreciate you trying to help and letting me know I can rename the car names, but that's not what I am reporting and not what would solve my (and possibly others) problem.  I believe (being a web developer) that the value of the drop-down should be the car id, something that is unique, not the name that could be the same and that the user would want to call them the same (unless there is somehow a limitation of what you can set the value of the drop-down to.)

**Comment by borgstrom** [comment] 2024-08-07 00:14
I understand what @edgararroyo is asking for here, because I just encountered this exact situation.

I had a vehicle with the name CAR (not really its name, but the name doesn't matter). I took that vehicle to Tesla and traded it in as part of a purchase of a new vehicle. I think the name of the original vehicle still suits the new vehicle so I also name it CAR.

Now, in the Teslamate settings UI both vehicles are displayed as tabs at the top of the screen, both the same name. Data collection for both vehicles works as expected.

However, in the Grafana UI the dropdowns for selecting a vehicle no longer work because of this query: 

https://github.com/teslamate-org/teslamate/blob/cabb474504f915a7e3e2ff83735230f08ed06410/grafana/dashboards/drives.json#L1509-L1531

I currently just run Teslamate in a container and don't know enough to know what the correct way to "fix" this is but the problem is that `SELECT name AS __text` means only a single entry ends up in the dropdown. This could be fixed by something like `SELECT CONCAT(id, name) AS __text`, but I think that having everyone's grafana change the dropdown value change would be jarring and the wrong fix.

Hopefully this illustrates the issue so that someone who is familiar with all this can come up with a real fix. For now I'm just going to manually edit my `cars` table directly since the old vehicle will no longer cause the names to be updated since it doesn't show up in my Tesla account anymore.

**Comment by swiffer** [comment] 2024-09-23 03:55
I could modify the Cars Query to show a counter next to the Cars if two or more are named the same *without performance impact. Should it be done? @JakobLichterfeld

**Comment by cwanja** [comment] 2024-09-23 03:57
> I could modify the Cars Query to show a counter next to the Cars if two or more are named the same *without performance impact. Should it be done? @JakobLichterfeld 

Could it show `Car name - [last four or six of VIN]`?

**Comment by swiffer** [comment] 2024-09-23 04:02
Yes, works as well

**Comment by edgararroyo** [comment] 2024-09-23 04:03
I like the VIN idea, better to track.  Count (or number) could change unless you plan on using the car id and not just adding a sequential number.

**Comment by swiffer** [comment] 2024-09-23 06:06
@edgararroyo - could you try changing the variable query for car_id to the one below and post a screenshot of the result.

i'll update all dashboards while working on #2736

```sql
select
	id as __value,
	case when count(id) over (partition by name) > 1 then concat(name, right(vin, 6)) else name end as __text 
from cars
order by display_priority asc, name asc, vin asc
```

**Comment by JakobLichterfeld** [comment] 2024-09-23 09:10
> Should it be done?

As we do have now at minimum two users reporting the same thing, we can change it with the lowest priority, as it is not an issue but an UX improvement.

> Could it show `Car name - [last four or six of VIN]`?

I also vote for this idea

**Comment by edgararroyo** [comment] 2024-09-23 11:29
Can you add a dash between name and right(vin, 6)?   concat(name, '-', right(vin, 6))
Otherwise it works as intented, only add the last 6 VIN if more than 1 of the same name.

**Closed** 2024-09-29 09:19 UTC
Labels: enhancement, area:dashboard
